/** Declaration file generated by dts-gen */

export const signsInOrder: string[];

export const signsList: {
    AQUARIUS: string;
    ARIES: string;
    CANCER: string;
    CAPRICORN: string;
    GEMINI: string;
    LEO: string;
    LIBRA: string;
    PISCES: string;
    SAGITTARIUS: string;
    SCORPIO: string;
    TAURUS: string;
    VIRGO: string;
};

export const signsRanges: {
    endDay: number;
    endMonth: number;
    sign: string;
    startDay: number;
    startMonth: number;
}[];

export function areSignsOpposite(signA: any, signB: any): any;

export function getCompleteSignInfo(sign: any): any;

export function getElement(sign: any): any;

export function getModality(sign: any): any;

export function getOppositeSign(sign: any): any;

export function getSign(date: any, format: any): any;

